### PR TITLE
stringify null values to string

### PR DESCRIPTION
**Pull request by hankim813**
Mailchimp will also apparently reject requests if you send them traits that are `null`.
So I am stringifying them just like we are doing that for boolean values.

Now it's important to document that if you are creating custom merge fields inside Mailchimp and you know that you are sending either `boolean` or `null` value, you must set that merge field's data type as `TEXT`. If you don't it will not be accepted by Mailchimp due to differing data types. Since there is really no way to guess if a `null` object should be converted to `0` by Segment, we're going to be consistent and stringify all values since Mailchimp doesn't allow you to create a custom merge field with those exact data types.

@dominicbarnes

### CODE REVIEW

**Comment by pauloschilling** [comment]
Hi @hankim813, can you confirm which values a TEXT merge field is MailChimp supposed to store when receiving a boolean trait from Segment? (`false` => ? , `true` => ? , `null` => ?)

I remember that in the beginning it was '1' (for true) and '' (empty, for false), but during my last tests a few days ago I identified some records as 'true' and 'false' (both strings).

**Comment by hankim813** [comment]
@pauloschilling yeah we tested how the new api handles boolean values. It was dropping requests that were sending `boolean` values because there is no way to set a data type for a custom merge field(CMF) as "boolean". 

You are right in that previously I think Mailchimp was converting them to 1 for true and empty for false. This would've been fine but because they reject the requests if the data type of what we send them does not match exactly what you set as the custom merge field data type. 

So the case was that because Mailchimp doesn't provide the data type of "Boolean" for the CMF, most users were choosing "TEXT". So we started stringifying the `boolean` values Segment received as strings as passing them through. So now you will just see them as `true` or `false`.

Same thing with a `null` value. Since we are stringifying `boolean` values as well we decided to keep it consistent and stringify the `null` value as well since people that send a `user.trait` that can have a value of `null` is most likely going to be sending a string value in the event that the user.trait is not `null`.

We made it clear in the newly updated docs that in the event you are sending `user.traits` that may contain `boolean` or `null` values, you want to create a `TEXT` CMF.

Hope that helps!

**Comment by pauloschilling** [comment]
Great, @hankim813, thank you for this useful explanation!

All this makes sense, we've been using `boolean` traits as `string` merge fields since the beginning, this was really the only way to make it work. Now we need to update MC's segments configuration accordingly, so if we used to filter like `FIELDX = '1'` now we have to filter as `FIELDX = 'true'`.

Thank you again.

**Comment by hankim813** [comment]
Sure no problem! We'll be looking to add more functionality to this integration such as MC's goals and such :)

Stay tuned!

**Pull request merged**
