### PR TITLE
Add option to override list id

### PR DESCRIPTION
**Pull request by f2prateek**
https://trello.com/c/jZZdLR91/204-mailchimp-add-lists-override-feature-a-la-drip-1

### CODE REVIEW

**Comment by f2prateek** [comment]
cc @segmentio/integrations , tested end to end!

**Comment by f2prateek** [comment]
As per our discussion in https://trello.com/c/OYJj8a8B/181-unsubscribe-api, we'll want to move away from subscribing automatically via identify, but that's a much bigger change across all integrations so this is good for now.

**Comment by DirtyAnalytics** [comment]
@f2prateek is this one ready? I had a customer ask for it today

**Comment by f2prateek** [comment]
@DirtyAnalytics yup it is, tested end to end, but still needs a review from someone else. ping @segmentio/integrations

**Comment by amillet89** [comment]
lgtm!

**Comment by DirtyAnalytics** [comment]
how do i know when stuff is live after a fix like this gets merged? right when the merge happens? or when there's a new tagged release? https://github.com/segmentio/integration-mailchimp/commit/69f4dc1cdaf00e8f0bb2ab6a3a1ccb032719b58c

or something else?

**Comment by f2prateek** [comment]
cc @gjohnson would know

**Pull request merged**
