### PR TITLE
fixed language

### PR DESCRIPTION
**Pull request by stevenmiller888**
@DirtyAnalytics This fixes the language problem. It actually needs to be sent in `merge_vars` rather than at the top-level.

### CODE REVIEW

**Comment by DirtyAnalytics** [comment]
Thanks Steven!

**Comment by f2prateek** [comment]
Could you squash these commits? LGTM otherwise

**Comment by stevenmiller888** [comment]
@f2prateek Squashed!

**Comment by DirtyAnalytics** [comment]
is this deployed?

**Comment by DirtyAnalytics** [comment]
looks like the latest deploy was 7 days ago so I assume not... can we push it out tomorrow?

**Comment by f2prateek** [comment]
I'm out until Monday, could we have someone else with robo deploy this one?

**Comment by DirtyAnalytics** [comment]
@stevenmiller888 ?

**Comment by stevenmiller888** [comment]
Happy to if there's some documentation somewhere. Haven't deployed a server-side integration before.

**Comment by DirtyAnalytics** [comment]
tag team with @ndhoule ?

**Comment by dominicbarnes** [comment]
@DirtyAnalytics @stevenmiller888 I've tagged and deployed this as `1.1.0`

**Comment by f2prateek** [comment]
@stevenmiller888 also docs for deploying are here https://segmentio.hackpad.com/Engineering-Deploying-Server-Side-Integrations-jUL2NVoi6yg

**Comment by f2prateek** [comment]
@dominicbarnes Why did we release this one as a minor version bump instead of a patch release?

**Pull request merged**
