### PR TITLE
map language

### PR DESCRIPTION
**Pull request by DirtyAnalytics**
real basic addition here... based on https://apidocs.mailchimp.com/api/2.0/lists/subscribe.php

@f2prateek @ndhoule @amillet89

### CODE REVIEW

**Comment by DirtyAnalytics** [comment]
maybe i should get help from @stevenmiller888 @lambtron or @sperand-io haha can you guys figure out why my code sucks?

**Comment by DirtyAnalytics** [comment]
@stevenmiller888 @lambtron @sperand-io i might need your help here

**Comment by pauloschilling** [comment]
What about using `identify.proxy` instead of `facade.proxy`?

**Comment by DirtyAnalytics** [comment]
I'm not sure what the difference is TBH... I just used the same code as this: https://github.com/segmentio/integration-amplitude/blob/master/lib/mapper.js#L136

**Comment by pauloschilling** [comment]
Here:

```js
function locale(facade){
  var locale = facade.proxy('context.locale');
```

You're receiving `facade` as a param, but on your code `exports.identify = function(identify){` you're receiving just `identify` as a param.

**Comment by DirtyAnalytics** [comment]
well that fixed the build :)

**Comment by stevenmiller888** [comment]
Lgtm now!

**Comment by f2prateek** [comment]
Needs tests! Ping me tomorrow and I can finish it up.

**Comment by barrymazza** [comment]
YES! Thank you for fixing

**Comment by DirtyAnalytics** [comment]
@f2prateek can you help write the tests? I haven't written tests for a server-side integration like this so not sure how it's done.

**Comment by f2prateek** [comment]
@DirtyAnalytics whoops sorry I forgot about this, I'll write them up tomorrow without fail.

**Comment by f2prateek** [comment]
Closing for #10

**Pull request closed without merging**
